### ISSUE TITLE
Add second placetux location to the bot

### ISSUE THREAD

**Issue by owenwastaken** [r-PlaceTux/placetux-bot#21]
A second placetux location has been created at (300, 1250) and is already in the [place_tux overlay](https://github.com/r-PlaceTux/place_tux)

**Comment by marens101** [comment]
https://r-placetux.github.io/place_tux/foss_raw.png

**Comment by marens101** [comment]
@owenwastaken Use those coords and this image link, or check announcements in Discord for the other way which supports both spots at once.

**Comment by owenwastaken** [comment]
@marens101 what is the link to the discord?

**Comment by owenwastaken** [comment]
The second tux is no longer being placed. Closing this issue
