### ISSUE TITLE
ERROR - Failed to connect to websocket, trying again in 30 seconds...

### ISSUE THREAD

**Issue by SlashAcorn** [r-PlaceTux/placetux-bot#24]
# Bug Report Form

## Checklist

- [X] I am using the latest version of the code.
- [X] I am absolutely sure I read the README in its entirety.
- [X] I have made sure this is not a duplicate issue.
- [x] I have filled out this form correctly.

## Describe the bug

When I run `./start.sh` it tells me the requirements are satisfied and starts an image update, it updates the image and loads the image after 3 minutes I get `ERROR - Failed to connect to websocket, trying again in 30 seconds...` even though I have websocket installed.

## To Reproduce

Steps to trigger the bug:
1. run start .sh
2. wait ~3 minutes

## Expected behavior

The expected behavior is that it connects to reddit and places a tile every 5 minutes 

below is my config.json
`{
    "image_start_coords": [20, 679],
    "thread_delay": 2,
    "unverified_place_frequency": false,
    "proxies": ["1.1.1.1:8080","2.2.2.2:1234"],
    "compact_logging": true,
    "image_hash_url": "https://r-placetux.github.io/place_tux/bot_hash",
    "image_url": "https://r-placetux.github.io/place_tux/tux_raw.png",
    "workers": {
        "SlashAcorn_": {
            "password": "mypassword",
            "start_coords": [0, 0]
        }
      }
    }`

**Comment by cappig** [comment]
Remove the "proxies" field from the config. This is a upstream issue, see https://github.com/rdeepak2002/reddit-place-script-2022/issues/357
